image: adoptopenjdk:13-jdk-hotspot

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - template: Code-Quality.gitlab-ci.yml

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # Put GRADLE_USER_HOME into the cache directory so the wrapper is not
  # re-downloaded for every job.
  - export GRADLE_USER_HOME=/cache/.gradle

cache:
  key: ${CI_COMMIT_REF_SLUG}

stages:
  - build
  - test

build:
  stage: build
  tags:
    - opentcs-runner
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/distributions/*.zip
    reports:
      junit: openTCS-*/build/test-results/test/TEST-*.xml
    when: always

code_quality:
  stage: test
  tags:
    - opentcs-runner
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags
